Member 활동 api 연동 및 컴포넌트 추가
KGU-C-Lab/clab.page pull request #192
Opened 2024-08-08 09:58 UTC by Jeong-Ag

## Summary
>#39

Member 내 활동 api를 연동하고 필요한 컴포넌트를 생성합니다.

## Tasks

- 활동 그룹 생성 페이지 추가
- UTC로 나타나는 시간을 KST로 변경
- GroupCard의 이미지 크기 수정
- 관리 페이지 내에 활동 그룹 관리 section 추가
- 활동 신청 시 존재하는 그룹이 1개일 경우 선택이 되지 않는 문제 보완
- 활동 페이지 내에서 참여자 조회 시 현재 활동에 참여 중인 인원만 나타나도록 수정

## ETC

- 과제 제출 및 조회 부분 연동 진행되었으나 백엔드 api 수정으로 인해 보완할 부분이 있을 것으로 예상되어 서버 배포 이후 수정 후 PR 예정입니다. 
- 활동 그룹 정보 수정 API 연동은 이번주 중으로 마무리 할 예정입니다.
- [feat(member): add activity group create page (](https://github.com/KGU-C-Lab/clab.page/commit/dcc5bf308c4e6179318fd3462b6b3f74298fe2c8)#39) 의 커밋 메세지가 잘못 입력된 것을 push 이후에 확인했습니다. force push를 사용하여 수정해도 문제 없다면 커밋 메세지는 수정하도록 하겠습니다. 앞으로 꼭 확인 후 커밋하겠습니다.

## Screenshot
<img width="980" alt="스크린샷 2024-08-08 오후 3 35 47" src="https://github.com/user-attachments/assets/81d83605-b395-45b7-9f1d-e3f3fc513baf">
<img width="1792" alt="스크린샷 2024-08-08 오후 3 34 00" src="https://github.com/user-attachments/assets/ef627372-0cac-4e3f-ba18-d08aee2a07c6">
<img width="1792" alt="스크린샷 2024-08-08 오후 3 34 04" src="https://github.com/user-attachments/assets/6f5ca5cf-7fd3-450a-be2e-cf8d80c14e2c">
<img width="1034" alt="스크린샷 2024-08-08 오후 3 34 51" src="https://github.com/user-attachments/assets/67d60408-8b00-40d8-aada-54f55b2c6fc8">
<img width="1792" alt="스크린샷 2024-08-08 오후 3 34 55" src="https://github.com/user-attachments/assets/4d82fb66-01d0-44b7-bbf6-0b6d04dcb6ef">

2024-08-08 12:49 UTC, gwansikk commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +  const options = [
변경이 없는 데이터는 컴포넌트 외에 선언하여 사용하는 것이 좋아요

2024-08-08 13:03 UTC, gwansikk commented on apps/member/src/components/manage/ManageActivitySection/ManageActivitySection.tsx
> +  const handleInfoButtonClick = (groupId: number) => {
Good, 앞으로 React Event Handler 이름 명명을 이와 같이 하려고 해요.
접두사를 `handle`, 접미사를 이벤트명(`Click`)으로 다른 컴포넌트에도 적용해주세요.
(e.g. `handleInfoButtonClick`, `handleNameChange`)

2024-08-08 13:24 UTC, gwansikk requested changes

2024-08-08 13:24 UTC, gwansikk commented on apps/member/src/components/manage/ManageActivitySection/ManageActivitySection.tsx
> +            <Table.Row key={index}>
`key`는 최대한 고유한 키로 지정하는게 좋아요 (리액트 최적화 관련)
고유한 키를 지정할 수 없는 경우라면, 최대한 index를 활용하여 고유한 키 조합으로 지정하도록 합니다

- https://ko.react.dev/learn/rendering-lists

2024-08-08 13:24 UTC, gwansikk commented on apps/member/src/constants/environment.ts
> +export const UNSPLASH_ACCESS_KEY: TEnvironmentValue = import.meta.env
Good 👍👍

2024-08-08 13:31 UTC, gwansikk commented
@Jeong-Ag 커밋 메세지는 영어로 작성할 필요는 없어요..! (후배 인수인계를 위해)

2024-08-09 02:10 UTC, gwansikk approved these changes
LGTM

2024-08-09 02:11 UTC, merged

2024-08-09 02:17 UTC, SWARVY reviewed
수고많으셨습니다 :)

2024-08-09 02:17 UTC, SWARVY commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +];
`ActivityGroupCategoryType`이 만들어져있지만, 해당 부분을 지금처럼 string형태로 기입을 하게된다면 휴먼 에러가 발생할 것 같아요

해당 부분을 상수로 분리하여 관리하고 `ActivityGroupCategoryType`을 다시 작성해보시는건 어떨까요?

```ts
const ACTIVITY_GROUP_CATEGORY_TYPE = {
  study: 'STUDY',
  name: 'NAME',
} as const

...

type ActivityGroupType = (typeof ACTIVITY_GROUP_TYPE)[keyof typeof ACTIVITY_GROUP_TYPE]
```

이런식으로 사용하게된다면 상수인 `ACTIVITY_GROUP_TYPE`을 로드하여 사용하면서 오타와 같은 휴먼에러를 방지할 수 있고, 추후 카테고리의 확장이 유연하게 가능할 것 같아요

2024-08-09 02:17 UTC, SWARVY commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +}
`Effective Typescript` 책에서 다뤄지는 내용인데, string의 타입을 조금 더 구체화해보는 것은 어떨까요?

[Item33. string타입보다 더 구체적인 타입 사용하기](https://velog.io/@ssulv3030/Effective-TypeScript-%ED%83%80%EC%9E%85-%EC%84%A4%EA%B3%841)

해당사항이 없는거라면 패스하시면 됩니다~

2024-08-09 02:17 UTC, SWARVY commented on apps/member/src/api/activity.ts
> + */
주석처리로 기능에 대한 설명을 달아놓으신게 보기 좋네요 👍🏻

2024-08-09 02:17 UTC, SWARVY commented on apps/member/src/components/manage/ManageActivitySection/ManageActivitySection.tsx
> +  const renderMode = {
저같은경우는 상수 컨벤션을

변수명 -> 대문자 스네이크 케이스
내부 key -> 소문자 카멜 케이스

로 사용해요, 혹시 이런식으로 상수 케이스를 사용하시는 이유가 따로 있을까요?
제가 사용하는 컨벤션 링크 첨부합니다 :) [Airbnb JS Style Guide 23.10](https://github.com/ParkSB/javascript-style-guide#naming--uppercase)

2024-08-14 16:57 UTC, Jeong-Ag commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +            />
https://github.com/KGU-C-Lab/clab-platforms/pull/201/commits/6b85683c3c466e8b3cd3e777e68724ce3943cbfb 묶어서 리팩토링 하니 훨씬 깔끔하네요 👏👏

2024-08-14 16:57 UTC, Jeong-Ag commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +];
https://github.com/KGU-C-Lab/clab-platforms/pull/201/commits/2c883d0cef105dc68e2db9a0f5346f9cde03586a 해당 내용 반영하여 리팩토링 진행하였습니다! 새로운 방식으로 선언해본 type이라서 학습에 도움이 되었어요 감사합니다 :-)

2024-08-14 16:58 UTC, Jeong-Ag commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +}
해당 코드에는 적용할 부분이 없어서 다른 타입 선언 시에 구체화해서 나타내보도록 하겠습니다!!